### PR TITLE
Avoid leaking hostname on failed hostname verification

### PR DESCRIPTION
**Pull request by doodlesbykumbi**

### CODE REVIEW

**Review by BradleyBoutcher — APPROVED** [review]
LGTM

**Comment by izgeri** [comment]
what did we decide to do with this PR? were we going to move this logic into secretless, and did we do that?

thanks!

**Comment by doodlesbykumbi** [comment]
@izgeri I’m not really sure how to proceed. This PR doesn’t seem all that valuable in the backdrop of a myriad of other errors that will disclose the host name, whether we hide it here or in Secretless.

**Comment by izgeri** [comment]
this is one that we have control over, so we should hide it if we can (especially if we can logically do it by catching a certain type of error)

it's ok with me if we file an issue to follow up with this logic in secretless, though - @doodlesbykumbi can you file the issue, reference it here, and close this PR?

**Comment by doodlesbykumbi** [comment]
Closed in favour of https://github.com/cyberark/secretless-broker/issues/1229

**Pull request closed without merging**
